# Generated by Django 3.0.7 on 2021-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildCron', '0006_auto_20210720_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('security_level', models.TextField()),
            ],
        ),
    ]
